name: 'Deploy LWTV Documentation Plugin'

on:
  push:
    branches: [ main ]

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Do a git checkout including submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Verify Workspace
        run: |
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
      - name: Verify Folder
        run: |
          ls -lah ${GITHUB_WORKSPACE}

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.LWTV_STATUS_SSH_KEY }}
          ARGS: "-rlgoDzvc -i"
          REMOTE_HOST: ${{ secrets.LWTV_DOCS_HOST }}
          REMOTE_USER: ${{ secrets.LWTV_STATUS_USER }}
          TARGET: ${{ secrets.LWTV_DOCS_TARGET }}plugins/lwtv-docs-plugin/
          EXCLUDE: "/.git/, /.github/"
